# HTML
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'Yuko Azure Plugin Test'
    applications: '3caa69a7-2e04-4949-ad83-6f6cd940d2da'
    scanname: 'Test'
    scantype: 'static'
    scanMethod: 'IRX'
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'Yuko Azure Plugin Test'
    applications: '3caa69a7-2e04-4949-ad83-6f6cd940d2da'
    scantype: 'static'
    scanMethod: 'IRXless'
    includeSCAFile: true
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
